version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build: .
    restart: always
    ports:
      - 127.0.0.1:80:8000
    depends_on:
      - postgres
      - redis
  celery_worker:
          build: .
          restart: always
          command: celery -A project worker -l info
          environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS='*'
          depends_on:
            - app
            - redis
  redis:
    image: redis:5-alpine
    ports:
    - 127.0.0.1:5672:6379