version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.prod