FROM qivi/dt_test:latest

WORKDIR /usr/app

COPY requirements.txt .

RUN apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install -r requirements.txt

COPY . .

CMD ["python", "manage.py", "runserver"]