version: '3'
services:
  postgres:
    environment:
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.build
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env.prod
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.build
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.build