version: '3'
services:
  postgres:
    image: postgres
    restart: always
  app:
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:80:8000
    depends_on:
      - postgres
      - redis
  celery_worker:
    restart: always
    command: celery -A project worker -l info
    depends_on:
      - app
      - redis
  celery_beat:
    restart: always
    command: celery -A project beat -l info
    depends_on:
      - app
      - redis
  redis:
    image: library/redis:3-alpine
