# Generated by Django 3.2 on 2021-04-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_post_comment_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authon_name',
            new_name='author_name',
        ),
    ]
