version: "2.1"

orbs:
  irc: circleci/irc@0.2.0

jobs:
  build:
    working_directory: ~/dt_test/DT_test
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.build.yml up -d
            docker-compose run app python manage.py test
      - deploy:
          name: Publish application Docker image
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker image tag dttest_app $DOCKER_HUB_USER_ID/dt_test:$CIRCLE_SHA1
            docker image tag dttest_app $DOCKER_HUB_USER_ID/dt_test:latest
            docker push $DOCKER_HUB_USER_ID/dt_test:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dt_test:latest
      - run:
          name: Deploy in production
          command: |
            ssh $AZURE_USERNAME@$PRODUCTION_IP $AZURE_USER_PASSWORD
            git pull origin master
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker-compose -f docker-compose.yml -f docker-compose.build.yml -f docker-compose.prod.yml up --build -d
      - irc/notify:
          channel: circle-notify
          message: Build completed!
