version: "2.1"
jobs:
  build:
    working_directory: ~/dt_test/DT_test
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          environment:
            ENV: prod
          name: Run tests
          command: |
            pwd
            ls
            docker-compose up -d
            docker-compose run app ls
            docker-compose run app pwd
            docker-compose run app python manage.py test
      - deploy:
          name: Publish application Docker image
          command: |
            docker ps
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dt_proj_app $DOCKER_HUB_USER_ID/dt_test:$CIRCLE_SHA1
            docker tag dt_proj_app $DOCKER_HUB_USER_ID/dt_test:latest
            docker push $DOCKER_HUB_USER_ID/dt_test:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dt_test:latest